# Generated by Django 4.2.7 on 2023-11-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManager',
            fields=[
            ],
            options={
                'verbose_name': 'Client Manager',
                'verbose_name_plural': 'Client Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
