# Generated by Django 4.2.7 on 2023-11-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0003_clientmanager'),
        ('contracts', '0002_alter_contract_vat_declaration_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_manager_contracts', to='users.clientmanager', verbose_name='Client Manager'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='client_manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.clientmanager', verbose_name='Client Manager'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client Name'),
        ),
    ]
